import { PermissionCategoryDef } from './types';

export const CATEGORIES_PART_3: PermissionCategoryDef[] = [
  {
    id: 'cat-11',
    number: 11,
    name: 'Employees, timecards & schedules',
    description: 'Timecards, breaks, schedule creation, shift swaps, wage viewing/setting, and profile access.',
    permissions: [
      { id: 'emp_clock_in_out', name: 'Clock In / Out', description: 'Record own work time' },
      { id: 'emp_start_end_breaks', name: 'Start / End Breaks', description: 'Record own breaks within configured rules' },
      { id: 'emp_view_own_timecards', name: 'View Own Timecards', description: 'View personal time entries' },
      { id: 'emp_req_timecard_corr', name: 'Request Timecard Corrections', description: 'Submit a correction request' },
      { id: 'emp_view_team_timecards', name: 'View Team Timecards', description: 'View others’ time entries' },
      { id: 'emp_edit_team_timecards', name: 'Edit Team Timecards', description: 'Make audited corrections to others’ entries' },
      { id: 'emp_approve_timecard_corr', name: 'Approve Timecard Corrections', description: 'Approve submitted corrections' },
      { id: 'emp_approve_attend_excep', name: 'Approve Attendance Exceptions', description: 'Approve permitted clock-in or break exceptions' },
      { id: 'emp_view_team_schedule', name: 'View Team Schedule', description: 'View published staff schedules' },
      { id: 'emp_create_edit_schedules', name: 'Create / Edit Schedules', description: 'Prepare schedules' },
      { id: 'emp_publish_schedules', name: 'Publish Schedules', description: 'Release schedules to employees' },
      { id: 'emp_approve_shift_changes', name: 'Approve Shift Changes', description: 'Approve swaps, coverage, and time-off requests' },
      { id: 'emp_view_employee_profiles', name: 'View Employee Profiles', description: 'View basic staff details' },
      { id: 'emp_create_employees', name: 'Create Employees', description: 'Add employees' },
      { id: 'emp_edit_employee_profiles', name: 'Edit Employee Profiles', description: 'Update basic employee information' },
      { id: 'emp_deactivate_employees', name: 'Deactivate Employees', description: 'Disable employee access' },
      { id: 'emp_assign_approved_jobs', name: 'Assign Approved Jobs', description: 'Assign operational jobs within authority' },
      { id: 'emp_manage_job_defs', name: 'Manage Job Definitions', description: 'Create/edit job types' },
      { id: 'emp_view_wages', name: 'View Employee Wages', description: 'See compensation details' },
      { id: 'emp_set_wages', name: 'Set / Change Employee Wages', description: 'Add or update pay rates' },
      { id: 'emp_export_payroll', name: 'Export Payroll Data', description: 'Export authorized payroll information' },
      { id: 'emp_reset_credentials', name: 'Reset Employee Credentials', description: 'Reset permitted employees’ PINs or cards' },
    ],
  },
  {
    id: 'cat-12',
    number: 12,
    name: 'Reports & audit history',
    description: 'Separate View and Export permissions for financial, operational, and audit reports.',
    permissions: [
      { id: 'rpt_view_own_sales', name: 'View Own Sales Reports', description: 'View personal sales and performance' },
      { id: 'rpt_export_own_sales', name: 'Export Own Sales Reports', description: 'Export personal sales data' },
      { id: 'rpt_view_loc_sales', name: 'View Location Sales Reports', description: 'View revenue, sales totals, and trends' },
      { id: 'rpt_export_loc_sales', name: 'Export Location Sales Reports', description: 'Export location revenue data' },
      { id: 'rpt_view_payment', name: 'View Payment Reports', description: 'View tender totals and transaction summaries' },
      { id: 'rpt_export_payment', name: 'Export Payment Reports', description: 'Export tender and payment summaries' },
      { id: 'rpt_view_discount_comp', name: 'View Discount & Comp Reports', description: 'View discounts and complimentary items' },
      { id: 'rpt_export_discount_comp', name: 'Export Discount & Comp Reports', description: 'Export discount and comp records' },
      { id: 'rpt_view_void_refund', name: 'View Void & Refund Reports', description: 'View cancellations and refunded payments' },
      { id: 'rpt_export_void_refund', name: 'Export Void & Refund Reports', description: 'Export void and refund records' },
      { id: 'rpt_view_service_fee', name: 'View Service Fee Reports', description: 'View collected, removed, and adjusted charges' },
      { id: 'rpt_export_service_fee', name: 'Export Service Fee Reports', description: 'Export service charge logs' },
      { id: 'rpt_view_cash_closeout', name: 'View Cash & Closeout Reports', description: 'View drawer balances and discrepancies' },
      { id: 'rpt_export_cash_closeout', name: 'Export Cash & Closeout Reports', description: 'Export drawer closeout data' },
      { id: 'rpt_view_menu_perf', name: 'View Menu Performance Reports', description: 'View item/category sales' },
      { id: 'rpt_export_menu_perf', name: 'Export Menu Performance Reports', description: 'Export menu item sales performance' },
      { id: 'rpt_view_inv_waste', name: 'View Inventory & Waste Reports', description: 'View counts, movements, and waste' },
      { id: 'rpt_export_inv_waste', name: 'Export Inventory & Waste Reports', description: 'Export inventory & waste counts' },
      { id: 'rpt_view_cost_margin', name: 'View Cost & Margin Reports', description: 'View food costs and profitability' },
      { id: 'rpt_export_cost_margin', name: 'Export Cost & Margin Reports', description: 'Export food cost and margin reports' },
      { id: 'rpt_view_labor_hours', name: 'View Labor Hours Reports', description: 'View hours and attendance' },
      { id: 'rpt_export_labor_hours', name: 'Export Labor Hours Reports', description: 'Export hours and attendance logs' },
      { id: 'rpt_view_wage_labor_cost', name: 'View Wage & Labor Cost Reports', description: 'View compensation and labor expense' },
      { id: 'rpt_export_wage_labor_cost', name: 'Export Wage & Labor Cost Reports', description: 'Export labor cost data' },
      { id: 'rpt_view_tip', name: 'View Tip Reports', description: 'View tip collection and distribution' },
      { id: 'rpt_export_tip', name: 'Export Tip Reports', description: 'Export tip data' },
      { id: 'rpt_view_guest', name: 'View Guest Reports', description: 'View customer activity' },
      { id: 'rpt_export_guest', name: 'Export Guest Reports', description: 'Export customer metrics' },
      { id: 'rpt_view_gift_loyalty', name: 'View Gift Card & Loyalty Reports', description: 'View balances and reward activity' },
      { id: 'rpt_export_gift_loyalty', name: 'Export Gift Card & Loyalty Reports', description: 'Export gift card and loyalty logs' },
      { id: 'rpt_view_multi_loc', name: 'View Multi-Location Reports', description: 'View consolidated location data' },
      { id: 'rpt_export_multi_loc', name: 'Export Multi-Location Reports', description: 'Export consolidated location data' },
      { id: 'rpt_view_check_audit', name: 'View Check Audit History', description: 'View order/check changes and actors' },
      { id: 'rpt_export_check_audit', name: 'Export Check Audit History', description: 'Export check audit trail' },
      { id: 'rpt_view_emp_activity', name: 'View Employee Activity Logs', description: 'View employee actions' },
      { id: 'rpt_export_emp_activity', name: 'Export Employee Activity Logs', description: 'Export employee log activity' },
      { id: 'rpt_view_permission_logs', name: 'View Permission & Approval Logs', description: 'View access changes and supervisor approvals' },
      { id: 'rpt_export_permission_logs', name: 'Export Permission & Approval Logs', description: 'Export approval and access change logs' },
    ],
  },
  {
    id: 'cat-13',
    number: 13,
    name: 'Gift cards, loyalty & house accounts',
    description: 'Gift card sales/reloads, balance adjustments, loyalty redemption, and customer house accounts.',
    permissions: [
      { id: 'gft_sell_reload', name: 'Sell / Reload Gift Cards', description: 'Add value against a recorded payment' },
      { id: 'gft_view_balances', name: 'View Gift Card Balances', description: 'Check available balances' },
      { id: 'gft_adjust_balances', name: 'Adjust Gift Card Balances', description: 'Change value outside normal sale', hasDollarLimit: true },
      { id: 'gft_transfer_balances', name: 'Transfer Gift Card Balances', description: 'Move value between cards' },
      { id: 'gft_deactivate_cards', name: 'Deactivate Gift Cards', description: 'Block cards' },
      { id: 'gft_enroll_loyalty', name: 'Enroll Loyalty Members', description: 'Register guests' },
      { id: 'gft_redeem_loyalty', name: 'Redeem Loyalty Rewards', description: 'Apply earned rewards' },
      { id: 'gft_adjust_loyalty_pts', name: 'Adjust Loyalty Points', description: 'Add/remove points manually' },
      { id: 'gft_merge_loyalty_accts', name: 'Merge Loyalty Accounts', description: 'Combine duplicate accounts' },
      { id: 'gft_issue_cust_credits', name: 'Issue Customer Credits', description: 'Grant account credit', hasDollarLimit: true },
      { id: 'gft_adjust_cust_credits', name: 'Adjust Customer Credits', description: 'Correct or revoke credit' },
      { id: 'gft_create_house_acct', name: 'Create / Edit House Accounts', description: 'Manage customer charge accounts' },
      { id: 'gft_set_house_limits', name: 'Set House Account Limits', description: 'Configure credit limits', hasDollarLimit: true },
      { id: 'gft_config_rules', name: 'Configure Gift Card / Loyalty Rules', description: 'Change program settings' },
    ],
  },
  {
    id: 'cat-14',
    number: 14,
    name: 'Delivery, invoices & catering',
    description: 'Driver dispatch, delivery updates, catering events, estimates, and invoice collections.',
    permissions: [
      { id: 'dlv_view_assigned', name: 'View Assigned Deliveries', description: 'View own delivery assignments' },
      { id: 'dlv_update_assigned', name: 'Update Assigned Deliveries', description: 'Update own delivery progress' },
      { id: 'dlv_view_all', name: 'View All Deliveries', description: 'View delivery activity across location' },
      { id: 'dlv_dispatch_drivers', name: 'Dispatch / Reassign Drivers', description: 'Assign or change drivers' },
      { id: 'dlv_cancel_dispatch', name: 'Cancel Dispatch', description: 'Return delivery to unassigned queue' },
      { id: 'dlv_correct_deliveries', name: 'Correct Completed Deliveries', description: 'Make audited delivery corrections' },
      { id: 'dlv_view_invoices', name: 'View Estimates & Invoices', description: 'Read documents' },
      { id: 'dlv_create_edit_invoices', name: 'Create / Edit Estimates & Invoices', description: 'Prepare documents' },
      { id: 'dlv_send_invoices', name: 'Send Estimates & Invoices', description: 'Send documents to customers' },
      { id: 'dlv_collect_invoice_pay', name: 'Collect Invoice Payments', description: 'Record supported invoice payments' },
      { id: 'dlv_cancel_invoices', name: 'Cancel Invoices / Issue Credits', description: 'Cancel amounts owed or issue credit notes' },
      { id: 'dlv_view_catering', name: 'View Catering Events', description: 'View event bookings' },
      { id: 'dlv_manage_catering', name: 'Manage Catering Events', description: 'Create/edit bookings and orders' },
      { id: 'dlv_config_delivery_catering', name: 'Configure Delivery / Catering', description: 'Change module settings' },
    ],
  },
  {
    id: 'cat-15',
    number: 15,
    name: 'System, devices & admin security',
    description: 'Hardware configuration, security policies, multi-location copy, role management, and system updates.',
    permissions: [
      { id: 'sys_edit_rest_details', name: 'Edit Restaurant Details', description: 'Change contact details, hours, and branding' },
      { id: 'sys_config_pos_behavior', name: 'Configure POS Behavior', description: 'Change order and register behavior' },
      { id: 'sys_config_payment_methods', name: 'Configure Payment Methods', description: 'Enable/configure supported tenders' },
      { id: 'sys_config_printers', name: 'Configure Printers', description: 'Change printers and routing' },
      { id: 'sys_config_cash_drawers', name: 'Configure Cash Drawer Devices', description: 'Change hardware assignments' },
      { id: 'sys_config_terminals', name: 'Configure Terminals & Readers', description: 'Change terminal/card-reader settings' },
      { id: 'sys_manage_network', name: 'Manage Network Settings', description: 'Change supported network configuration' },
      { id: 'sys_manage_browser_access', name: 'Manage Approved Browser Access', description: 'Configure permitted browser tools' },
      { id: 'sys_publish_changes', name: 'Publish System Changes', description: 'Release configuration changes' },
      { id: 'sys_sched_changes', name: 'Schedule Configuration Changes', description: 'Schedule approved updates' },
      { id: 'sys_manage_locations', name: 'Manage Locations', description: 'Create/edit location settings' },
      { id: 'sys_copy_settings_loc', name: 'Copy Settings Between Locations', description: 'Apply configuration across locations' },
      { id: 'sys_view_emp_perms', name: 'View Employee Permissions', description: 'Inspect role and employee access' },
      { id: 'sys_manage_role_perms', name: 'Manage Role Permissions', description: 'Change permissions granted by roles' },
      { id: 'sys_manage_emp_overrides', name: 'Manage Employee Overrides', description: 'Grant/revoke individual exceptions' },
      { id: 'sys_grant_elevated_roles', name: 'Grant Elevated Roles', description: 'Assign administrative or supervisory access' },
      { id: 'sys_manage_approval_limits', name: 'Manage Approval Limits', description: 'Configure who can approve actions and amounts' },
      { id: 'sys_manage_integrations', name: 'Manage Integrations', description: 'Configure connected services' },
      { id: 'sys_install_remove_apps', name: 'Install / Remove Apps', description: 'Add/remove third-party applications' },
      { id: 'sys_manage_api_creds', name: 'Manage API Credentials', description: 'Create/revoke integration credentials' },
      { id: 'sys_config_auto_exports', name: 'Configure Automated Exports', description: 'Configure recurring data delivery' },
      { id: 'sys_manage_subs', name: 'Manage Subscriptions & Purchases', description: 'Change plans or authorize purchases' },
      { id: 'sys_view_deposits', name: 'View Deposits & Payouts', description: 'View settlement information' },
      { id: 'sys_manage_bank_payouts', name: 'Manage Bank / Payout Settings', description: 'Change financial destinations' },
      { id: 'sys_init_transfers', name: 'Initiate Supported Transfers', description: 'Initiate supported deposit/transfer actions' },
      { id: 'sys_data_retention', name: 'Manage Data Retention / Deletion', description: 'Perform controlled data administration' },
    ],
  },
];
