import { PermissionCategoryDef } from './types';

export const CATEGORIES_PART_1: PermissionCategoryDef[] = [
  {
    id: 'cat-1',
    number: 1,
    name: 'POS & application access',
    description: 'Control access to primary POS registers, terminals, displays, and modules.',
    permissions: [
      { id: 'pos_access_register', name: 'Access POS Register', description: 'Open the register and create customer orders', hasScope: true },
      { id: 'pos_access_table_service', name: 'Access Table Service', description: 'Use table-based ordering', hasScope: true },
      { id: 'pos_access_quick_order', name: 'Access Quick Order', description: 'Use counter-service/takeout ordering' },
      { id: 'pos_access_guest_mgr', name: 'Access Guest Manager', description: 'Open floor plan and guest-management tools' },
      { id: 'pos_access_reservations', name: 'Access Reservations & Waitlist', description: 'Open reservation and waitlist tools' },
      { id: 'pos_access_orders_hub', name: 'Access Orders Hub', description: 'View incoming and pending orders', hasScope: true },
      { id: 'pos_access_payment_terminal', name: 'Access Payment Terminal', description: 'Open payment collection tools' },
      { id: 'pos_access_kitchen_display', name: 'Access Kitchen Display', description: 'Open the kitchen display system' },
      { id: 'pos_access_delivery_mgmt', name: 'Access Delivery Management', description: 'Open delivery tools' },
      { id: 'pos_access_back_office', name: 'Access Back Office', description: 'Enter administrative interface (individual actions restricted)' },
      { id: 'pos_access_help_support', name: 'Access Help & Support', description: 'View help and troubleshooting tools' },
    ],
  },
  {
    id: 'cat-2',
    number: 2,
    name: 'Orders & checks',
    description: 'Permissions governing check creation, modification, splitting, transferring, and voids.',
    permissions: [
      { id: 'ord_create_orders', name: 'Create Orders', description: 'Start a new order/check' },
      { id: 'ord_view_own_orders', name: 'View Own Orders', description: 'View orders assigned to the employee' },
      { id: 'ord_view_other_orders', name: 'View Other Employees’ Orders', description: 'View other employees’ orders', hasScope: true },
      { id: 'ord_edit_own_orders', name: 'Edit Own Orders', description: 'Add or modify unsent items on own orders' },
      { id: 'ord_edit_other_orders', name: 'Edit Other Employees’ Orders', description: 'Add or modify unsent items on others’ orders' },
      { id: 'ord_remove_unsent_items', name: 'Remove Unsent Items', description: 'Remove items before kitchen submission' },
      { id: 'ord_send_to_kitchen', name: 'Send Orders to Kitchen', description: 'Submit items for preparation' },
      { id: 'ord_edit_sent_items', name: 'Edit Sent Items', description: 'Change items/modifiers already sent; notify the kitchen' },
      { id: 'ord_void_sent_items', name: 'Void Sent Items', description: 'Void individual items after submission' },
      { id: 'ord_void_entire_orders', name: 'Void Entire Orders', description: 'Void a complete open order' },
      { id: 'ord_add_special_requests', name: 'Add Special Requests', description: 'Add preparation notes and special instructions' },
      { id: 'ord_add_open_price_items', name: 'Add Open-Price Items', description: 'Enter an item not listed on the menu', hasDollarLimit: true },
      { id: 'ord_override_prices', name: 'Override Item Prices', description: 'Change an item’s price on a specific check', hasDollarLimit: true },
      { id: 'ord_hold_fire_items', name: 'Hold & Fire Items', description: 'Control when items/courses are sent' },
      { id: 'ord_change_order_type', name: 'Change Order Type', description: 'Switch between dine-in, takeout, or supported types' },
      { id: 'ord_split_checks', name: 'Split Checks', description: 'Divide an order into separate checks' },
      { id: 'ord_split_individual_items', name: 'Split Individual Items', description: 'Divide an item’s cost between checks' },
      { id: 'ord_merge_checks', name: 'Merge Checks', description: 'Combine checks' },
      { id: 'ord_transfer_items', name: 'Transfer Items Between Checks', description: 'Move items from one check to another' },
      { id: 'ord_transfer_own_checks', name: 'Transfer Own Checks', description: 'Assign own checks to another employee' },
      { id: 'ord_reassign_other_checks', name: 'Reassign Other Employees’ Checks', description: 'Change ownership of others’ checks' },
      { id: 'ord_search_historical', name: 'Search Historical Checks', description: 'Find previous orders' },
      { id: 'ord_reopen_closed_checks', name: 'Reopen Closed Checks', description: 'Reopen completed check without auto edit rights' },
      { id: 'ord_edit_reopened_checks', name: 'Edit Reopened Checks', description: 'Modify eligible reopened check with audit trail' },
      { id: 'ord_reprint_kitchen_tickets', name: 'Reprint Kitchen Tickets', description: 'Reprint tickets with duplicate indicator' },
      { id: 'ord_bulk_transfer_checks', name: 'Bulk Transfer Checks', description: 'Reassign multiple checks' },
      { id: 'ord_bulk_void_orders', name: 'Bulk Void Orders', description: 'Void multiple open orders' },
      { id: 'ord_bulk_close_paid_checks', name: 'Bulk Close Paid Checks', description: 'Close multiple fully paid checks' },
    ],
  },
  {
    id: 'cat-3',
    number: 3,
    name: 'Tables, reservations & guests',
    description: 'Floor plan management, table status, reservations, waitlists, and guest CRM profiles.',
    permissions: [
      { id: 'tbl_view_floor_plan', name: 'View Floor Plan', description: 'View tables, occupancy, and service status' },
      { id: 'tbl_seat_guests', name: 'Seat Guests', description: 'Assign a party to a table' },
      { id: 'tbl_update_status', name: 'Update Table Status', description: 'Mark tables available, occupied, dirty, or reserved' },
      { id: 'tbl_move_occupied', name: 'Move Occupied Tables', description: 'Move a party/check to another table' },
      { id: 'tbl_combine_separate', name: 'Combine / Separate Tables', description: 'Combine tables for seating or separate them' },
      { id: 'tbl_assign_servers_sections', name: 'Assign Servers & Sections', description: 'Assign staff to tables or sections' },
      { id: 'tbl_edit_layout', name: 'Edit Floor Plan Layout', description: 'Add, remove, resize, or reposition tables' },
      { id: 'tbl_edit_details', name: 'Edit Table Details', description: 'Change table names, capacities, and sections' },
      { id: 'tbl_create_reservations', name: 'Create Reservations', description: 'Add bookings' },
      { id: 'tbl_edit_reservations', name: 'Edit Reservations', description: 'Change booking details' },
      { id: 'tbl_cancel_reservations', name: 'Cancel Reservations', description: 'Cancel bookings' },
      { id: 'tbl_override_res_limits', name: 'Override Reservation Limits', description: 'Bypass configured capacity or booking restrictions' },
      { id: 'tbl_manage_waitlist', name: 'Manage Waitlist', description: 'Add, edit, remove, or seat waitlisted parties' },
      { id: 'tbl_change_waitlist_priority', name: 'Change Waitlist Priority', description: 'Reorder the waitlist' },
      { id: 'tbl_send_guest_notifs', name: 'Send Guest Notifications', description: 'Send approved operational messages' },
      { id: 'tbl_view_guest_profiles', name: 'View Guest Profiles', description: 'View basic guest information' },
      { id: 'tbl_edit_guest_profiles', name: 'Edit Guest Profiles', description: 'Create/update guest contact information' },
      { id: 'tbl_view_guest_history', name: 'View Guest History', description: 'View prior visits and orders' },
      { id: 'tbl_manage_guest_notes', name: 'Manage Guest Notes', description: 'Add/edit standard preferences and notes' },
      { id: 'tbl_view_restricted_notes', name: 'View Restricted Guest Notes', description: 'Read sensitive internal notes' },
      { id: 'tbl_edit_restricted_notes', name: 'Edit Restricted Guest Notes', description: 'Create/change sensitive internal notes' },
      { id: 'tbl_merge_guest_profiles', name: 'Merge Guest Profiles', description: 'Combine duplicate profiles' },
      { id: 'tbl_export_guest_data', name: 'Export Guest Data', description: 'Download customer information' },
      { id: 'tbl_config_res_settings', name: 'Configure Reservation Settings', description: 'Change availability, rules, and deposit settings' },
    ],
  },
  {
    id: 'cat-4',
    number: 4,
    name: 'Payments & refunds',
    description: 'Payment tender handling, card terminals, split payments, and partial/full refund limits.',
    permissions: [
      { id: 'pay_accept_card', name: 'Accept Card Payments', description: 'Collect payments through supported card readers' },
      { id: 'pay_accept_cash', name: 'Accept Cash Payments', description: 'Record cash payments' },
      { id: 'pay_redeem_gift_cards', name: 'Redeem Gift Cards', description: 'Accept gift cards as payment' },
      { id: 'pay_accept_custom_tenders', name: 'Accept Custom Payment Types', description: 'Use approved vouchers or configured tenders' },
      { id: 'pay_charge_house_acct', name: 'Charge House Accounts', description: 'Apply check to approved customer account' },
      { id: 'pay_take_payment_others', name: 'Take Payment on Others’ Orders', description: 'Collect payment for another employee’s check' },
      { id: 'pay_split_payments', name: 'Split Payments', description: 'Accept multiple payments on one check' },
      { id: 'pay_manual_card_entry', name: 'Manually Enter Cards', description: 'Enter card details through processor interface' },
      { id: 'pay_use_virtual_terminal', name: 'Use Virtual Terminal', description: 'Process supported remote payments' },
      { id: 'pay_offline_cards', name: 'Accept Offline Card Payments', description: 'Process offline payments within limits', hasDollarLimit: true },
      { id: 'pay_override_offline_limit', name: 'Override Offline Payment Limits', description: 'Authorize higher-risk offline payments' },
      { id: 'pay_void_unsettled', name: 'Void Unsettled Payments', description: 'Cancel eligible payment before settlement' },
      { id: 'pay_issue_partial_refund', name: 'Issue Partial Refunds', description: 'Refund part of a payment', hasDollarLimit: true },
      { id: 'pay_issue_full_refund', name: 'Issue Full Refunds', description: 'Refund an entire payment', hasDollarLimit: true },
      { id: 'pay_refund_previous_day', name: 'Refund Previous-Day Payments', description: 'Refund payments from earlier business days', hasAgeLimit: true, hasDollarLimit: true },
      { id: 'pay_issue_unlinked_refund', name: 'Issue Unlinked Refunds', description: 'Refund without linked transaction (disabled by default)', hasDollarLimit: true },
      { id: 'pay_refund_alt_tender', name: 'Refund to Alternative Tender', description: 'Refund using different tender (disabled by default)' },
      { id: 'pay_view_history', name: 'View Transaction History', description: 'View payment records within assigned scope', hasScope: true },
      { id: 'pay_print_resend_receipts', name: 'Print / Resend Receipts', description: 'Provide printed or digital receipts' },
    ],
  },
  {
    id: 'cat-5',
    number: 5,
    name: 'Discounts, comps, service fees & taxes',
    description: 'Promotional discounts, item comps, auto-gratuity, service charges, and tax exemptions.',
    permissions: [
      { id: 'dsc_preset_discounts', name: 'Apply Preset Discounts', description: 'Use approved discounts or promo codes' },
      { id: 'dsc_custom_percent_dsc', name: 'Apply Custom Percentage Discounts', description: 'Enter a percentage discount', hasPercentLimit: true },
      { id: 'dsc_custom_amount_dsc', name: 'Apply Custom Amount Discounts', description: 'Enter a dollar discount', hasDollarLimit: true },
      { id: 'dsc_item_discounts', name: 'Apply Item Discounts', description: 'Discount selected items' },
      { id: 'dsc_check_discounts', name: 'Apply Entire-Check Discounts', description: 'Discount the whole check' },
      { id: 'dsc_stack_discounts', name: 'Stack Discounts', description: 'Apply multiple discounts where supported' },
      { id: 'dsc_exceed_limits', name: 'Exceed Discount Limits', description: 'Exceed normal discount cap' },
      { id: 'dsc_comp_items', name: 'Comp Items', description: 'Make selected items complimentary', hasDollarLimit: true },
      { id: 'dsc_comp_entire_checks', name: 'Comp Entire Checks', description: 'Make an entire check complimentary', hasDollarLimit: true },
      { id: 'dsc_remove_discounts', name: 'Remove Applied Discounts', description: 'Remove an existing discount' },
      { id: 'dsc_apply_preset_svc_fee', name: 'Apply Preset Service Fees', description: 'Add approved service charges' },
      { id: 'dsc_remove_svc_fees', name: 'Remove Service Fees', description: 'Remove an applied service charge' },
      { id: 'dsc_adjust_svc_fees', name: 'Adjust Service Fee Amounts', description: 'Change a charge on a specific check' },
      { id: 'dsc_create_edit_svc_rules', name: 'Create / Edit Service Fee Rules', description: 'Configure service charge types and auto application' },
      { id: 'dsc_apply_auto_grat', name: 'Apply Automatic Gratuity', description: 'Apply an approved automatic gratuity' },
      { id: 'dsc_adjust_auto_grat', name: 'Remove / Adjust Automatic Gratuity', description: 'Change automatic gratuity on a check' },
      { id: 'dsc_override_happy_hour', name: 'Override Happy-Hour Pricing', description: 'Apply pricing outside configured conditions' },
      { id: 'dsc_apply_tax_exemption', name: 'Apply Tax Exemption', description: 'Exempt transaction with required details' },
      { id: 'dsc_manage_discount_rules', name: 'Manage Discount Rules', description: 'Create/edit discounts, codes, and schedules' },
      { id: 'dsc_manage_happy_hour_rules', name: 'Manage Happy-Hour Rules', description: 'Configure promotional pricing schedules' },
      { id: 'dsc_manage_tax_rules', name: 'Manage Tax Rules', description: 'Change tax rates and tax assignments' },
    ],
  },
];
