import { PermissionCategoryDef } from './types';

export const CATEGORIES_PART_2: PermissionCategoryDef[] = [
  {
    id: 'cat-6',
    number: 6,
    name: 'Cash drawers & closeout',
    description: 'Cash management, drops, paid outs, drawer assignments, blind counts, and daily closeout.',
    permissions: [
      { id: 'csh_assigned_drawer', name: 'Use Assigned Cash Drawer', description: 'Operate assigned drawer during cash transactions' },
      { id: 'csh_open_no_sale', name: 'Open Drawer Without Sale', description: 'Open drawer without taking payment' },
      { id: 'csh_other_drawers', name: 'Access Other Cash Drawers', description: 'Operate drawers outside employee assignment' },
      { id: 'csh_record_in', name: 'Record Cash In', description: 'Record money added to a drawer' },
      { id: 'csh_record_drops', name: 'Record Cash Drops', description: 'Record money moved from drawer to safe' },
      { id: 'csh_record_payouts', name: 'Record Cash Payouts', description: 'Record authorized cash expenses' },
      { id: 'csh_view_log', name: 'View Cash Log', description: 'View cash movements within assigned scope', hasScope: true },
      { id: 'csh_assign_drawers', name: 'Open / Assign Cash Drawers', description: 'Start drawer sessions and assign staff' },
      { id: 'csh_adjust_start_bal', name: 'Adjust Starting Balance', description: 'Change opening cash amount' },
      { id: 'csh_blind_count', name: 'Submit Blind Cash Count', description: 'Enter counted cash without viewing expected amount' },
      { id: 'csh_view_expected', name: 'View Expected Cash Balance', description: 'See what a drawer should contain' },
      { id: 'csh_close_drawers', name: 'Close Cash Drawers', description: 'Complete drawer reconciliation' },
      { id: 'csh_approve_over_short', name: 'Approve Excess Over / Short', description: 'Approve discrepancies above limit', hasDollarLimit: true },
      { id: 'csh_own_shift_review', name: 'Complete Own Shift Review', description: 'Submit own shift checkout' },
      { id: 'csh_review_other_shifts', name: 'Review Other Employees’ Shifts', description: 'Review others’ sales, payments, and checkout' },
      { id: 'csh_close_biz_day', name: 'Close Business Day', description: 'Complete location-level closeout' },
      { id: 'csh_reopen_biz_day', name: 'Reopen Business Day', description: 'Reopen previously closed day' },
      { id: 'csh_correct_cash_records', name: 'Correct Historical Cash Records', description: 'Make tracked corrections to prior cash records' },
      { id: 'csh_config_auto_close', name: 'Configure Automatic Closeout', description: 'Change automatic closing behavior' },
    ],
  },
  {
    id: 'cat-7',
    number: 7,
    name: 'Tips',
    description: 'Tip declaration, tip adjustments, team tip reporting, tip pool rules, and payouts.',
    permissions: [
      { id: 'tip_view_own', name: 'View Own Tips', description: 'View personal tip totals' },
      { id: 'tip_enter_own', name: 'Enter Own Tips', description: 'Enter tips for own eligible payments' },
      { id: 'tip_edit_own_unsettled', name: 'Edit Own Unsettled Tips', description: 'Correct own tips before settlement/lock' },
      { id: 'tip_edit_other_tips', name: 'Edit Other Employees’ Tips', description: 'Correct another employee’s tips' },
      { id: 'tip_adjust_after_closeout', name: 'Adjust Tips After Closeout', description: 'Make audited post-closeout corrections' },
      { id: 'tip_declare_cash', name: 'Declare Cash Tips', description: 'Record cash tips received' },
      { id: 'tip_view_team_reports', name: 'View Team Tip Reports', description: 'View other employees’ tip information' },
      { id: 'tip_record_payouts', name: 'Record Tip Payouts', description: 'Record tips paid to employees' },
      { id: 'tip_manage_pool_rules', name: 'Manage Tip Pool Rules', description: 'Configure tip-sharing rules' },
      { id: 'tip_approve_distribution', name: 'Approve Tip Distribution', description: 'Approve calculated payouts or adjustments' },
    ],
  },
  {
    id: 'cat-8',
    number: 8,
    name: 'Menu & pricing',
    description: 'Menu creation, items, modifiers, pricing, recipe costing, and KDS routing.',
    permissions: [
      { id: 'mnu_view_mgmt', name: 'View Menu Management', description: 'View menu configuration' },
      { id: 'mnu_create_items', name: 'Create Menu Items', description: 'Add new items' },
      { id: 'mnu_edit_item_details', name: 'Edit Item Details', description: 'Change descriptions, images, and standard names' },
      { id: 'mnu_edit_pos_names', name: 'Edit POS Display Names', description: 'Change names shown to staff' },
      { id: 'mnu_archive_items', name: 'Archive Menu Items', description: 'Remove items from sale while preserving history' },
      { id: 'mnu_manage_cat_menus', name: 'Manage Categories & Menus', description: 'Create/reorganize categories and multiple menus' },
      { id: 'mnu_manage_modifiers', name: 'Manage Modifiers', description: 'Create/edit modifier groups, options, and requirements' },
      { id: 'mnu_edit_prices', name: 'Edit Menu Prices', description: 'Change standard selling prices' },
      { id: 'mnu_edit_location_prices', name: 'Edit Location-Specific Prices', description: 'Change prices for authorized locations' },
      { id: 'mnu_manage_scheduled_prices', name: 'Manage Scheduled Prices', description: 'Configure time-based pricing' },
      { id: 'mnu_rearrange_buttons', name: 'Rearrange Menu Buttons', description: 'Change item order and button appearance' },
      { id: 'mnu_manage_item_tax', name: 'Manage Item Tax Assignments', description: 'Assign approved tax categories' },
      { id: 'mnu_manage_kitchen_routing', name: 'Manage Kitchen Routing', description: 'Assign items to preparation stations/printers' },
      { id: 'mnu_edit_recipes', name: 'Edit Recipes & Ingredients', description: 'Change recipes and ingredient usage' },
      { id: 'mnu_view_recipe_costs', name: 'View Recipe Costs & Margins', description: 'View food costs and calculated margins' },
      { id: 'mnu_publish_changes', name: 'Publish Menu Changes', description: 'Make draft menu updates live' },
    ],
  },
  {
    id: 'cat-9',
    number: 9,
    name: 'Inventory & purchasing',
    description: 'Stock levels, 86ing items, stock counts, waste tracking, purchase orders, and supplier costs.',
    permissions: [
      { id: 'inv_view_stock', name: 'View Stock Levels', description: 'View available inventory' },
      { id: 'inv_mark_86_available', name: 'Mark Items Sold Out / Available', description: 'Change availability without editing menu' },
      { id: 'inv_update_avail_qty', name: 'Update Available Quantities', description: 'Set sellable quantities' },
      { id: 'inv_enter_counts', name: 'Enter Inventory Counts', description: 'Record physical counts' },
      { id: 'inv_adjust_stock', name: 'Adjust Inventory', description: 'Make stock corrections with reason' },
      { id: 'inv_record_waste', name: 'Record Waste', description: 'Record spoilage, excess food, and breakage' },
      { id: 'inv_transfer_stock', name: 'Transfer Stock', description: 'Move inventory between authorized locations' },
      { id: 'inv_receive_stock', name: 'Receive Stock', description: 'Record incoming deliveries' },
      { id: 'inv_create_po', name: 'Create Purchase Orders', description: 'Draft stock orders' },
      { id: 'inv_approve_po', name: 'Approve Purchase Orders', description: 'Authorize purchases within limits', hasDollarLimit: true },
      { id: 'inv_manage_suppliers', name: 'Manage Suppliers', description: 'Create/edit vendor information' },
      { id: 'inv_view_purchase_costs', name: 'View Purchase Costs', description: 'View supplier and ingredient costs' },
      { id: 'inv_edit_purchase_costs', name: 'Edit Purchase Costs', description: 'Update cost information' },
      { id: 'inv_config_rules', name: 'Configure Inventory Rules', description: 'Change units, thresholds, and stock-tracking' },
    ],
  },
  {
    id: 'cat-10',
    number: 10,
    name: 'Kitchen & online order operations',
    description: 'Kitchen display workflow, ticket bumping/recalling, online order controls, and prep time updates.',
    permissions: [
      { id: 'kds_view_tickets', name: 'View Kitchen Tickets', description: 'View tickets for assigned stations' },
      { id: 'kds_update_prep_status', name: 'Update Preparation Status', description: 'Mark items preparing or ready' },
      { id: 'kds_bump_tickets', name: 'Bump / Complete Tickets', description: 'Remove completed tickets from active queue' },
      { id: 'kds_recall_tickets', name: 'Recall Tickets', description: 'Restore completed tickets' },
      { id: 'kds_change_priority', name: 'Change Ticket Priority', description: 'Prioritize tickets' },
      { id: 'kds_view_other_stations', name: 'View Other Kitchen Stations', description: 'Access stations outside default assignment' },
      { id: 'kds_accept_reject_online', name: 'Accept / Reject Incoming Orders', description: 'Act on incoming online orders' },
      { id: 'kds_adjust_prep_times', name: 'Adjust Quoted Prep Times', description: 'Change displayed preparation estimates' },
      { id: 'kds_pause_online_ordering', name: 'Pause / Resume Online Ordering', description: 'Temporarily control incoming order availability' },
      { id: 'kds_config_workflow', name: 'Configure KDS Workflow', description: 'Change station and ticket-handling settings' },
      { id: 'kds_config_online_ordering', name: 'Configure Online Ordering', description: 'Change ordering schedules and rules' },
    ],
  },
];
